### ISSUE TITLE
Missing `pla` module when building the project.

### ISSUE THREAD

**Issue by QRXqrx** [gryan11/PLA#1]
Hi there,

I tried to build the project following your instructions but I failed to run the `scripts/predict_races.py` due to the lack of module `pla`. I noticed there is no file named `pla.py` under the project. Would the source code of the module `pla` be publicized later? I'm very much looking forward to it.

**Comment by gryan11** [comment]
Sorry about that, I've added missing modules. Please let me know if you run into any other issues with running the project.

**Comment by QRXqrx** [comment]
Thanks a lot!
